# Project for Applied Statistics

In [5]:
# Mathematical functions from the standard library.
# https://docs.python.org/3/library/math.html
import math

# Permutations and combinations.
# https://docs.python.org/3/library/itertools.html
import itertools

# Random selections.
# https://docs.python.org/3/library/random.html
import random

# Numerical structures and operations.
# https://numpy.org/doc/stable/reference/index.html#reference
import numpy as np

# Plotting.
# https://matplotlib.org/stable/contents.html
import matplotlib.pyplot as plt

# Statistics.
import scipy.stats as stats

# Data frames.
import pandas as pd

In [8]:
# Read csv file into a pandas dataframe
df = pd.read_csv("PlantGrowth.csv")
df.head()

   rownames  weight group
0         1    4.17  ctrl
1         2    5.58  ctrl
2         3    5.18  ctrl
3         4    6.11  ctrl
4         5    4.50  ctrl

### Description of PlantGrowth R dataset:
https://vincentarelbundock.github.io/Rdatasets/doc/datasets/PlantGrowth.html


Results from an experiment to compare yields (as measured by dried weight of plants) obtained under a control and two different treatment conditions.

### Description of a t-test:
https://en.wikipedia.org/wiki/Student%27s_t-test

Student's t-test is a statistical test used to test whether the difference between the response of two groups is statistically significant or not. It is any statistical hypothesis test in which the test statistic follows a Student's t-distribution under the null hypothesis. It is most commonly applied when the test statistic would follow a normal distribution if the value of a scaling term in the test statistic were known (typically, the scaling term is unknown and is therefore a nuisance parameter). When the scaling term is estimated based on the data, the test statistic—under certain conditions—follows a Student's t distribution. The t-test's most common application is to test whether the means of two populations are significantly different. In many cases, a Z-test will yield very similar results to a t-test because the latter converges to the former as the size of the dataset increases.

In [12]:
#trt1 = df["group" : "trt1"]
trt1 = df[df['group'] == 'trt1']
trt1

    rownames  weight group
10        11    4.81  trt1
11        12    4.17  trt1
12        13    4.41  trt1
13        14    3.59  trt1
14        15    5.87  trt1
15        16    3.83  trt1
16        17    6.03  trt1
17        18    4.89  trt1
18        19    4.32  trt1
19        20    4.69  trt1

In [14]:
trt2 = df[df['group'] == 'trt2']
trt2

    rownames  weight group
20        21    6.31  trt2
21        22    5.12  trt2
22        23    5.54  trt2
23        24    5.50  trt2
24        25    5.37  trt2
25        26    5.29  trt2
26        27    4.92  trt2
27        28    6.15  trt2
28        29    5.80  trt2
29        30    5.26  trt2

In [15]:
ctrl = df[df['group'] == 'ctrl']
ctrl

   rownames  weight group
0         1    4.17  ctrl
1         2    5.58  ctrl
2         3    5.18  ctrl
3         4    6.11  ctrl
4         5    4.50  ctrl
5         6    4.61  ctrl
6         7    5.17  ctrl
7         8    4.53  ctrl
8         9    5.33  ctrl
9        10    5.14  ctrl